platform :ios,'8.0'
target "WPYCustomControls" do
pod 'IQKeyboardManager'
pod 'MBProgressHUD'
pod 'JPush'
pod 'Masonry'
pod 'FMDB'
pod 'MJRefresh'
pod 'SAMKeychain'
pod 'AFNetworking'
pod 'SDWebImage'
pod ‘UMengUShare/UI’
pod ‘UMengUShare/Social/WeChat'
pod ‘UMengUShare/Social/QQ'
pod ‘UMengUShare/Social/Sina'
pod ‘UMengUShare/Social/Twitter'
pod 'RongCloudIM/IMLib', '~> 2.8.3'
pod 'RongCloudIM/IMKit', '~> 2.8.3'
pod 'kingpin'
end
